networks:
  AUVSI-SUAS-Proxy-Network:
    ipam:
      config:
        - subnet: 163.20.0.0/16

services:
  mavproxy-rfd:
    profiles: ["mavproxy-rfd"]
    build: 
      context: .
      dockerfile: MavProxy.Dockerfile
    command: bash -c "mavproxy.py --master /dev/ttyUSB0 --out=tcpin:0.0.0.0:5770 --out=163.20.0.12:5750 --daemon"
    ports:
      - "127.0.0.1:5770:5770/tcp"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    privileged: true
    networks:
      AUVSI-SUAS-Proxy-Network:
        ipv4_address: 163.20.0.10
  
  mavrpoxy-pi:
    profiles: ["mavproxy-pi"]
    build: 
      context: .
      dockerfile: MavProxy.Dockerfile
    command: bash -c "mavproxy.py --master 0.0.0.0:14550 --out=tcpin:0.0.0.0:5770 --out=163.20.0.12:5750 --daemon"
    ports:
      - "127.0.0.1:5770:5770/tcp"
      - "14550:14550/udp"
    networks:
      AUVSI-SUAS-Proxy-Network:
        ipv4_address: 163.20.0.11
  
  interop-relay:
    build: 
      context: .
      dockerfile: InteropRelay.Dockerfile
    command: python relay.py --username dragobots --password P@ssw0rd --url http://164.92.120.251:8000/ --MavProxy 0.0.0.0:5750
    networks:
      AUVSI-SUAS-Proxy-Network:
        ipv4_address: 163.20.0.12
    
