networks:
  AUVSI-SUAS-Proxy-Network:
    ipam:
      config:
        - subnet: 163.20.0.0/16

services:
  mavproxy:
    build: 
      context: .
      dockerfile: dockerFiles/MavProxy.Dockerfile
    command: bash -c "mavproxy.py  --state-basedir=/home/mavproxy/logs/ --master=0.0.0.0:14555 --out=tcpin:0.0.0.0:5770 --out=tcpin:0.0.0.0:5780 --out=163.20.0.11:5750 --out=163.20.0.12:5750 --out=udpout:192.168.1.150:14550 --daemon"
    ports:
      - "5770:5770/tcp"
      - "5780:5780/tcp"
      - "14555:14555/udp"
      - "14550:14550/udp"
    volumes:
      - ./data/logs:/home/mavproxy/logs/
    networks:
      AUVSI-SUAS-Proxy-Network:
        ipv4_address: 163.20.0.10
  interop-relay:
    profiles:
      - interop
    build: 
      context: .
      dockerfile: dockerFiles/InteropRelay.Dockerfile
    command: python relay.py
    volumes:
      - ./interop-relay/relay.py:/home/interop/relay.py
      - ./config:/home/interop/config
    networks:
      AUVSI-SUAS-Proxy-Network:
        ipv4_address: 163.20.0.11
  proxy-server:
    build:
      context: .
      dockerfile: dockerFiles/ProxyServer.Dockerfile
    command: python server.py 
    ports:
      - "5000:5000/tcp"
    volumes:
      - ./proxyServer/server.py:/home/proxyServer/server.py
      - ./proxyServer/interop.py:/home/proxyServer/interop.py
      - ./config:/home/proxyServer/config
      - ./UAV-Data-Transmission/missionPool:/home/proxyServer/missionPool
      - ./proxyServer/files:/home/proxyServer/files
      - ./proxyServer/templates:/home/proxyServer/templates
      - ./control:/home/proxyServer/control
      - ./data/geolocations:/home/proxyServer/missions/geolocations
      - ./data/images:/home/proxyServer/missions/images
    networks:
      AUVSI-SUAS-Proxy-Network:
        ipv4_address: 163.20.0.12
